### ISSUE TITLE
Clay balls / clay block crafting repcipe

### ISSUE THREAD

**Issue by ghost** [ISenseHostility/Recipe-Enhancements#2]
I just found something - in version 1.5.2 for MC 1.16.5 - that you might wanna fix / switch around:

- The way it should be: Craft 4 clay balls with a clay block, right?!
- The way it is now: Craft 4 clay blocks with a clay ball.

**Comment by ISenseHostility** [comment]
Fixed in version 1.5.4, thank you.

**Comment by ghost** [comment]
Wow, that was fast. Thanks! Nice mod, btw. :-)
